### ISSUE TITLE
自动发布 对应平台版本

### ISSUE THREAD

**Issue by zuohuadong** [gaoyoubo/hexo-client#15]
参考： https://juejin.im/entry/5995599a6fb9a0249f6a131b

相关的实现可以看 https://github.com/nashaofu/dingtalk 
这个项目的  .travis.yml
以及 package.json 的  "release": "electron-builder"

以后再也不用自己慢慢打包了

**Comment by gaoyoubo** [comment]
> 参考： https://juejin.im/entry/5995599a6fb9a0249f6a131b
> 
> 相关的实现可以看 https://github.com/nashaofu/dingtalk
> 这个项目的 .travis.yml
> 以及 package.json 的 "release": "electron-builder"
> 
> 以后再也不用自己慢慢打包了

tks，我试下。

**Comment by gaoyoubo** [comment]
> 参考： https://juejin.im/entry/5995599a6fb9a0249f6a131b
> 
> 相关的实现可以看 https://github.com/nashaofu/dingtalk
> 这个项目的 .travis.yml
> 以及 package.json 的 "release": "electron-builder"
> 
> 以后再也不用自己慢慢打包了

我已经使用`AppVeyor`和`Travis`配置好自动构建了，非常感谢
