### ISSUE TITLE
七牛云域名要求备案，有没有可选的其它不需要备案的图片存储

### ISSUE THREAD

**Issue by icanfly** [gaoyoubo/hexo-client#16]
七牛云域名要求备案，有没有可选的其它不需要备案的图片存储，七牛的测试域名现在30天后回收了，是一个不稳定的域名，没法用了。。。备案太复杂了。

**Comment by gaoyoubo** [comment]
这个我倒是没有注意，因为我域名是备案过的，所以一直正常使用。我目前也没有其他合适的图片存储服务。欢迎推荐~

**Comment by gaoyoubo** [comment]
@icanfly hi, 新版本我会新增 https://sm.ms/ 图床支持。请关注下新版本。

**Comment by icanfly** [comment]
@gaoyoubo 期待。

**Comment by gaoyoubo** [comment]
@icanfly 请看下这个预览版本，已经支持了新的图床。

https://github.com/gaoyoubo/hexo-client/releases/tag/v1.2.3

**Comment by icanfly** [comment]
good, 这个图床稳定么，会不会过段时间就关了，这样的话就悲剧了

**Comment by icanfly** [comment]
还有就是，这个发布只是把源代码发布到git上，，，但是如果我是静态站点部署，这个时候可能需要的是执行本地的hexo命令进行静态打包上传呢

**Comment by gaoyoubo** [comment]
> good, 这个图床稳定么，会不会过段时间就关了，这样的话就悲剧了

这个图床相对很稳定，很多网友使用切评价很高。但是免费的东西保障肯定没那么高，如果有条件建议还是使用收费的。

**Comment by gaoyoubo** [comment]
> 还有就是，这个发布只是把源代码发布到git上，，，但是如果我是静态站点部署，这个时候可能需要的是执行本地的hexo命令进行静态打包上传呢

请看这篇文章：https://www.mspring.org/2018/11/29/HexoClient%E4%BD%BF%E7%94%A8%E5%B8%AE%E5%8A%A9/
我推荐的最佳实践方式是将hexo原文件提交上去之后，使用travis-ci自动部署到github pages。每次git push都会触发travis-ci去自动构建并deploy。hexo generate和hexo deploy都是在travis-ci上自动执行的。

**Comment by icanfly** [comment]
好的，谢谢
