### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by mohsenkhanpour** [gaoyoubo/hexo-client#17]
Any chance for the English version of this app?
I can help with the process.

**Comment by gaoyoubo** [comment]
Thanks for the feedback, I still don't support i18n, I am working on it.

**Comment by gaoyoubo** [comment]
@mohsenkhanpour hi，I have already supported the English version.

Preview version: https://github.com/gaoyoubo/hexo-client/releases/tag/v1.2.3
I18n file: https://github.com/gaoyoubo/hexo-client/blob/master/src/main/language.js

**Comment by mohsenkhanpour** [comment]
Thanks. Great work.
Do you need any help?

**Comment by mohsenkhanpour** [comment]
@gaoyoubo 	How to switch the language?

**Comment by gaoyoubo** [comment]
@mohsenkhanpour The program automatically reads the language of the current system and automatically selects the language based on the system language.

**Comment by gaoyoubo** [comment]
@mohsenkhanpour 
Hi, I upgraded the switch language feature.

![image](https://user-images.githubusercontent.com/2127168/50573776-33f05000-0e15-11e9-9b51-31706b76dce5.png)

**Comment by mohsenkhanpour** [comment]
@gaoyoubo Thanks, excellent work mate.
