### ISSUE TITLE
请求添加英文文件名

### ISSUE THREAD

**Issue by icanfly** [gaoyoubo/hexo-client#23]
目前软件使用上遇到的一个问题是，输入的标题自动生成的是中文文件名，发布的时候也是中文URL地址，希望是可以把标题和文件名区分开，标题用中文，文件名用英文，这样可能对于外文的搜索引擎更加友好。

建议新建文章输入标题处增加一个文件名的命名选项，默认如果不填写则以标题名命名

**Comment by icanfly** [comment]
PS: 感谢上次的指导，已经成功使用travis-ci发布文章，真心为这个软件的功能点赞！ #

**Comment by gaoyoubo** [comment]
> 目前软件使用上遇到的一个问题是，输入的标题自动生成的是中文文件名，发布的时候也是中文URL地址，希望是可以把标题和文件名区分开，标题用中文，文件名用英文，这样可能对于外文的搜索引擎更加友好。
> 
> 建议新建文章输入标题处增加一个文件名的命名选项，默认如果不填写则以标题名命名

这个可以，我放到下个版本计划中，最近工作比较忙，没时间弄。

**Comment by gaoyoubo** [comment]
> PS: 感谢上次的指导，已经成功使用travis-ci发布文章，真心为这个软件的功能点赞！ #

很高兴这个app能够帮到你。

**Comment by gaoyoubo** [comment]
@icanfly hi，新版本已经基本完成了，这个功能已经支持了，稍晚些打个包出来，邀请你体验下。
![image](https://user-images.githubusercontent.com/2127168/50825102-21c16500-1373-11e9-9951-ca0a1bf09832.png)
![image](https://user-images.githubusercontent.com/2127168/50825197-677e2d80-1373-11e9-943a-f0735e383b0f.png)

**Comment by icanfly** [comment]
期待！

**Comment by gaoyoubo** [comment]
该功能已经支持。
