### ISSUE TITLE
下载安装后页面空白无法使用MAC系统

### ISSUE THREAD

**Issue by sghyxp** [gaoyoubo/hexo-client#24]
怎么使用啊, 安装后打开一个空白页面没法操作啊

**Comment by gaoyoubo** [comment]
请问正确选择了hexo目录了吗？如果可以的话，请打开控制台看下有没有异常信息。

**Comment by sghyxp** [comment]
这个具体的使用操作有没有相关的文档或者博客啊, 新手不太会用呢,🤦‍♀️

**Comment by sghyxp** [comment]
我第一次安装选择的我之前本地使用hexo的block那个目录,然后后边再卸载安装就没有让选择地址了,只有**"查看"**里有个*切换开发者工具*点击会出来一个界面

**Comment by sghyxp** [comment]
我第一次安装选择的我之前本地使用hexo的block那个目录,然后后边再卸载安装就没有让选择地址了,只有"**查看**"里有个"*切换开发者工具*"点击会出来一个界面
