### ISSUE TITLE
无法设置发布的推送分支，或者当前分支

### ISSUE THREAD

**Issue by carpcai** [gaoyoubo/hexo-client#25]
我把源代码放在hexo分支，然后master分支用于存放hexo构建后的代码。
点击发布时，一直提示发布失败

![](http://cdn.carpcai.cn/localfile/6aef064317fe5108f41ef800eddbf2e5.jpg)

**Comment by carpcai** [comment]
图片：http://cdn.carpcai.cn/localfile/6aef064317fe5108f41ef800eddbf2e5.jpg

**Comment by carpcai** [comment]
本地当前分支一直是hexo，点击发布时，发布失败，但到当前目录使用git push就没问题。

**Comment by gaoyoubo** [comment]
@carpcai 谢谢反馈，我来排查下这个问题，修复了告诉你。

**Comment by carpcai** [comment]
Thank you, Your software is really awesome

**Comment by gaoyoubo** [comment]
> Thank you, Your software is really awesome

😊
