### ISSUE TITLE
Feature: 七牛云上传希望增加子文件夹功能

### ISSUE THREAD

**Issue by carpcai** [gaoyoubo/hexo-client#26]
我自己有七牛云cdn，但是我希望不同地方上传的文件可以分别归类，我看了下目前这个客户端的配置，只能默认配置到当前目录下

**Comment by gaoyoubo** [comment]
@carpcai 你希望将文件上传到`bucket/目录/文件`，而不是`bucket/文件`？

**Comment by carpcai** [comment]
@gaoyoubo  是的

**Comment by gaoyoubo** [comment]
@carpcai 我好像记得七牛没有目录的概念，我刚刚也测试了下， 是我用错了吗？ 
![image](https://user-images.githubusercontent.com/2127168/50808668-90ce9780-133a-11e9-9c20-066ee37dcfdc.png)

**Comment by carpcai** [comment]
![image](https://user-images.githubusercontent.com/17467462/50808901-b3ad7b80-133b-11e9-962c-66e0ccc42895.png)

试了下，效果是这样的。

![image](https://user-images.githubusercontent.com/17467462/50808918-cd4ec300-133b-11e9-921a-2a154401e700.png)

**Comment by carpcai** [comment]
就是前缀，看起来像目录哈哈， 我试了Bucket和域名无论怎么加后缀，上传都是 上传到根目录。

**Comment by gaoyoubo** [comment]
你的需求是希望图片能够加上统一的前缀吗？

**Comment by gaoyoubo** [comment]
@carpcai 七牛本身是不支持二级目录的，so~这种定制需求暂不考虑支持。
