### ISSUE TITLE
点击发布的时候，最近的几篇文章被重新定义了发布时间

### ISSUE THREAD

**Issue by icanfly** [gaoyoubo/hexo-client#27]
新增一篇文章，编辑完成后，点击发布，结果最近写的几篇文章的发布时间都变成了当前时间，，

**Comment by gaoyoubo** [comment]
hexo的发布实现是写到markdown文件的mate信息中的，和你什么时候点击发布时间并没有关系。

**Comment by icanfly** [comment]
但现实中我“新建”了一篇文章后，点击“发布”，然后就出现了之前的文章的时间都被改成了当前时间？

**Comment by gaoyoubo** [comment]
能将你的反馈的被修改了时间的文章原文件发给我下吗？ 就是markdown原文件。

**Comment by icanfly** [comment]
我大致知道原因了，是我的hexo的scaffolds下的post.md中没有日期的设置，加上日期的脚本架好像可以了。
date: {{ date }}

**Comment by gaoyoubo** [comment]
每太明白是什么原因。

**Comment by icanfly** [comment]
![image](https://user-images.githubusercontent.com/1010797/50824619-0a35ac80-1372-11e9-9e41-5acfbec96488.png)
这个文件里面的脚手架内容没有date这个字段，导致生成的文件里面没有date这个元数据，所以每次发布的时候文章都重新排成当前的日期了，，我之前操作没有问题，是因为我文章元数据都是手写的，会自己把date加上。。。如果你可以修复这个问题也是可以的。

**Comment by icanfly** [comment]
PS：文章的元数据可否开出来，让用户自己可以输入 ，这样的可操控性更强，:-)

**Comment by gaoyoubo** [comment]
已经支持front-matter 
![image](https://user-images.githubusercontent.com/2127168/57751438-53c74700-7718-11e9-8b9f-2fab2e87f6af.png)
