### ISSUE TITLE
点击发布，显示都是成功，但是实际博客中未显示

### ISSUE THREAD

**Issue by FutureNotFat** [gaoyoubo/hexo-client#33]
git push -u origin master
但是直接在本地git push 博客就自己更新了

**Comment by gaoyoubo** [comment]
@FutureNotFat  hexoclient推荐使用travis-ci进行自动发布。请参考这里进行配置。https://www.mspring.org/2018/11/29/HexoClient%E4%BD%BF%E7%94%A8%E5%B8%AE%E5%8A%A9/
