### ISSUE TITLE
希望支持LaTeX数学公式

### ISSUE THREAD

**Issue by zcy05331** [gaoyoubo/hexo-client#34]
如题，写数学公式时非常难受

**Comment by gaoyoubo** [comment]
感谢反馈，我抽空研究下。

**Comment by gaoyoubo** [comment]
hexo-client使用的是 https://github.com/hinesboy/mavonEditor ，我刚看了下，他是支持 KaTex 数据公式的，如下图：
![image](https://user-images.githubusercontent.com/2127168/53626812-ab8a0200-3c41-11e9-9777-68ef6aa421ee.png)
