### ISSUE TITLE
建议新增功能

### ISSUE THREAD

**Issue by zhangweixi** [gaoyoubo/hexo-client#38]
作者是否可以做一个新增 “文章简介”的功能呀，即原本的hexo模板中的description,现在虽然可以手动修改，但是每次更新后又使用了正式内容头部，导致文章网站上的首页格式很不优雅

**Comment by gaoyoubo** [comment]
description不属于hexo内定的文章属性，应该是你自定义的Front-matter，自定义Front-matter功能正在开发，已经基本上OK了，最近就会发布，详见：https://github.com/gaoyoubo/hexo-client/issues/32

**Comment by gaoyoubo** [comment]
最新版本已解决，欢迎体验：https://github.com/gaoyoubo/hexo-client/releases/tag/v1.2.6
