### ISSUE TITLE
建议新增留言板回复功能

### ISSUE THREAD

**Issue by ITfisher** [gaoyoubo/hexo-client#39]
收到留言能在客户端内提醒作者，并可以直接在客户端内进行回复。

**Comment by gaoyoubo** [comment]
hexo本身并没有留言功能，大家是用的留言功能都是使用的第三方服务，这个要怎么去做提醒呢？
请问下你是怎么实现的留言功能呢？

**Comment by ITfisher** [comment]
知道是第三方服务，我的意思是看看能不能模拟爬取第三方服务的留言，以及模拟回复留言。就好像上传七牛云、smms等图床那种，不都是通过接口模拟上传的么？就好像图床功能hexo也没有呀，也是调用的第三方。所以才建议看看能不能实现常见的留言插件得留言获取以及回复功能

**Comment by ITfisher** [comment]
比如多说、畅言、有言、disqus、gitment这种，实现一个或者多个看看行不行。不过我也没去研究过可行性以及实现难度，只是提一个建议和思路

**Comment by gaoyoubo** [comment]
@ITfisher 好的，感谢建议。 
多说、友言倒闭了，
畅言、gitment都需要登录授权，如果要做还需要模拟登录，成本很高。
disqus没研究过不太好下结论。
