### ISSUE TITLE
关于载入问题

### ISSUE THREAD

**Issue by sfzsjx** [gaoyoubo/hexo-client#41]
hexo-client 好像没办法将git上的文章载入到本地，或者选择自己需要发布文章，而不是所有的文章一起发布。不知道有什么方法可以解决吗？

**Comment by gaoyoubo** [comment]
没理解你描述的问题，能详细说一下吗？

**Comment by sfzsjx** [comment]
嗯，我的意思是像ideal 一样可以将git文章load到客户端。或者上传时指定自己需要上传的文件

**Comment by gaoyoubo** [comment]
明白了，现在是只能自己clone，并且上传的时候是提交所有的改动。你说的需求实现倒是没有问题，只是我之前没这个需求，而且也没人反馈过这个需求给我。
