### ISSUE TITLE
windows版本保存修改问题。

### ISSUE THREAD

**Issue by xunightmare** [gaoyoubo/hexo-client#44]
您好！我是windows用户。我今天发现昨天对博客的修改丢失了，原因是我没有点击保存按钮就直接关闭了软件。我知道这是我的操作失误，但是通过快捷键CTRL+S保存更加符合我的习惯。所以我想，能不能加入使用CTRL+S保存的功能，或者在关闭软件时也对未保存的修改进行提示呢？如果能够自动保存那就更好了！
谢谢您的阅读。

**Comment by gaoyoubo** [comment]
感谢反馈， 我抽空支持下。

**Comment by xunightmare** [comment]
感谢您在新版本中加入了我之前提到的功能！我在使用过程中，发现了一个小bug，新建了一篇博客之后，如果事先没有点击按钮保存，直接使用ctrl+s进行保存，如果按了多次ctrl+s，会出现重复保存的情况。
详情见视频：
链接：https://pan.baidu.com/s/1_A1RXnBod7Prwqmmlec6xg 
提取码：ozeg

**Comment by gaoyoubo** [comment]
好的，谢谢反馈我找下原因。

**Comment by gaoyoubo** [comment]
@xunightmare hi，已经修改多次ctrl+s，会出现重复的问题。

**Comment by gaoyoubo** [comment]
@xunightmare 请下载最新版本体验。

**Comment by xunightmare** [comment]
收到！感谢！
