### ISSUE TITLE
I love hexo, and your client, but would really like...

### ISSUE THREAD

**Issue by Anais-Et-Vous** [gaoyoubo/hexo-client#45]
... it to be in english. Is this possible? I don't mind helping with translations if you need it. We could translate through a service and I can check for proper language use?

**Comment by gaoyoubo** [comment]
hi，I have already supported the English version.
I18n files:  https://github.com/gaoyoubo/hexo-client/tree/master/src/locales

You can switch language in `Settings`

![image](https://user-images.githubusercontent.com/2127168/57280833-3b35ac00-70dc-11e9-8794-c59a18279490.png)
