### ISSUE TITLE
点击发布按钮，控制台报错

### ISSUE THREAD

**Issue by Xonlystar** [gaoyoubo/hexo-client#47]
![image](https://user-images.githubusercontent.com/19361551/56501631-081ee480-6542-11e9-82db-8c2e1da6375f.png)

**Comment by gaoyoubo** [comment]
做什么操作的时候报这个错误？

**Comment by Xonlystar** [comment]
我git clone你的项目，修改了部分界面样式，开发环境一切功能ok，但是打包后点击发布按钮就出现了这个错误，找了很久没发现原因。

**Comment by Xonlystar** [comment]
大神，你有没有遇到过这种问题啊，我只更改了界面，并没有改动功能，打包后就不能发布了，win和mac下都一样，求助啊

![image](https://user-images.githubusercontent.com/19361551/56561405-a8741800-65d9-11e9-8302-ccf6dcd62407.png)

**Comment by gaoyoubo** [comment]
没遇到过这种问题。

**Comment by gaoyoubo** [comment]
猜测应该是有的依赖包下载失败造成的。

**Comment by Xonlystar** [comment]
我用的npm装的，装完还有npm audit fix

**Comment by gaoyoubo** [comment]
你使用我的工程也有这种问题吗？

**Comment by Xonlystar** [comment]
是的，下载你的master分支也有这个问题

**Comment by Xonlystar** [comment]
我重装了好几遍环境，打包依然出现这样问题，不知道什么鬼

**Comment by Xonlystar** [comment]
经过不懈的努力，我找到了一个不是办法的办法，目前只能这样解决了。
经过对比发现，打包后找不到simple-git相关方法的路径，我修改了node_modules下simple-git的源码
```js
// node_modules/simple-git/src/git.js  1591行`requireResponseHandler`修改为
function requireResponseHandler (type) {
    return require('./responses/' + type)
}
```
