### ISSUE TITLE
撤销之后，没办法撤销之前的撤销

### ISSUE THREAD

**Issue by sy2729** [gaoyoubo/hexo-client#48]
一般Mac上撤销是Command + Z，撤销撤销是Command + Shift + Z，前者目前可以使用，希望能增加后者的快捷键，谢谢！

**Comment by gaoyoubo** [comment]
好的，谢谢反馈。

**Comment by gaoyoubo** [comment]
取消撤销快捷键为：CommandOrCtrl + Y
