### ISSUE TITLE
建议支持阿里云OSS作为图床

### ISSUE THREAD

**Issue by deanjoson** [gaoyoubo/hexo-client#50]
现在的七牛作为图床，域名是临时的，容易后期无法查看图片，而配置自定义域名需要有备案号才行。OSS如果用香港地区的室友免费5G的使用。速度也还好，希望能支持

**Comment by gaoyoubo** [comment]
现在免费的资源都不是很靠谱，其实我推荐直接使用github作为图床。hexoclient目前是支持的。

**Comment by lizhuangs** [comment]
> 现在免费的资源都不是很靠谱，其实我推荐直接使用github作为图床。hexoclient目前是支持的。

点进来才发现是hexo-client作者呢。我的博客目前是用的picgo上传到github，然后把图片同步到gitee。。。只是因为github太慢了。。所以，我推荐直接使用gitee做为图床也不错。至少，我很兴趣试试。哈哈~

**Comment by sy2729** [comment]
同一楼，希望能够支持阿里云OSS呀，七牛云域名备份太麻烦，然后Github上传慢……，sm.ms不太好管理也无法删除，求开发者支持阿里云OSS，放出二维码收费众筹此功能也可以😄（其实这样也比较好，不太好意思总是提出新需求哈哈）

**Comment by gaoyoubo** [comment]
@sy2729 改功能已经在启分支开发了，功能OK之后通知你们。

**Comment by sy2729** [comment]
@gaoyoubo 谢谢！

**Comment by gaoyoubo** [comment]
@deanjoson @lizhuangs @sy2729  已经支持阿里云oss图床了，请前往这里下载：
https://github.com/gaoyoubo/hexo-client/releases/tag/v1.2.8

**Comment by sy2729** [comment]
@gaoyoubo 谢谢大佬对于需求的关注，已打赏一杯奶茶钱～

**Comment by gaoyoubo** [comment]
@sy2729 感谢
