### ISSUE TITLE
不能够发布不能够发布

### ISSUE THREAD

**Issue by Duingold** [gaoyoubo/hexo-client#52]
![image](https://user-images.githubusercontent.com/21188624/61174739-feec6380-a5d6-11e9-94a2-6560d3bb3eee.png)

**Comment by gaoyoubo** [comment]
请问下，你的hexo源目录是基于git的吗？ 如果不是的话就会提示这个。

**Comment by Duingold** [comment]
是基于git的

**Comment by gaoyoubo** [comment]
@Duingold 可以帮忙打开控制台看一下有没有错误日志吗？

**Comment by Duingold** [comment]
![image](https://user-images.githubusercontent.com/21188624/61805223-0417a100-ae68-11e9-88ff-9c459b6f8089.png)

**Comment by gaoyoubo** [comment]
出现这个错误就一目了然了啊。你配置的`Hexo路径`没托管到git啊。 你去关于页面看下帮助文档。 
![image](https://user-images.githubusercontent.com/2127168/61839161-1a048080-aebf-11e9-9427-2b9e35eedcdf.png)
