### ISSUE TITLE
添加文章重复生成

### ISSUE THREAD

**Issue by SealinRepo** [gaoyoubo/hexo-client#56]
添加文章时按多次CTRL+S保存, 会产生多个重复的新文章

**Comment by gaoyoubo** [comment]
这个问题我已经发现并且修复了，我今天会重新发一版解决这个问题。

**Comment by gaoyoubo** [comment]
@SealinRepo 
bug已经修复，请下载最新版本：https://github.com/gaoyoubo/hexo-client/releases/tag/v1.2.9
