### ISSUE TITLE
把图片直接拖拽进编辑器后链接地址少个"/"

### ISSUE THREAD

**Issue by sy2729** [gaoyoubo/hexo-client#60]
把图片直接拖拽进编辑器后，出现的链接地址少个"/"，应该是代码里少了个/。比如本来链接是"http://baidu.com"，结果会变成"http:/baidu.com"，每次都需要手动补上。有时候忘了补，更新到网站图片就崩了。

**Comment by gaoyoubo** [comment]
请问你是使用的是哪种图床呢？ 七牛、阿里云、sm.ms还是Github？

**Comment by sy2729** [comment]
您好，我使用的是阿里云OSS

**Comment by gaoyoubo** [comment]
好的，感谢反馈， 我来看下。

**Comment by sy2729** [comment]
谢谢～
