### ISSUE TITLE
下载最新版本依然提示有新版本

### ISSUE THREAD

**Issue by Cybercll** [gaoyoubo/hexo-client#64]
RT

**Comment by Harlan-zh** [comment]
@gaoyoubo 我这里也有同样的问题

**Comment by gaoyoubo** [comment]
@Harlan-zh @Cybercll 感谢反馈，我调试一下。

**Comment by gaoyoubo** [comment]
@Harlan-zh @Cybercll 已经修复，请下载最新版本：1.3.1

**Comment by jeromememory** [comment]
哥 我这边更新之后 打开空白 下午都好使来着 刚才我在写博客 关了再打开就是一直空白状态 求解决
