### ISSUE TITLE
隐藏菜单样式乱了

### ISSUE THREAD

**Issue by Harlan-zh** [gaoyoubo/hexo-client#65]
@gaoyoubo 
![image](https://user-images.githubusercontent.com/53736226/62842324-e1004480-bce3-11e9-8793-94f14f39832b.png)
![image](https://user-images.githubusercontent.com/53736226/62842326-eb224300-bce3-11e9-9ae3-4c9be0a562e8.png)

**Comment by gaoyoubo** [comment]
请提供下你的系统呢。

**Comment by Harlan-zh** [comment]
@gaoyoubo   windows 10 version 1903

**Comment by gaoyoubo** [comment]
已经修复，请下载最新版本：1.3.1

**Comment by Harlan-zh** [comment]
@gaoyoubo 好的
