### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by jeromememory** [gaoyoubo/hexo-client#67]
mac系统下 使用了挺久一直没问题 但是今天打开后一片空白 无法修复

**Comment by gaoyoubo** [comment]
好的，我现在看下。

**Comment by jeromememory** [comment]
是啊 我卸载了然后重下也不行了...还下了以前的几个版本...我就昨天写完博客 关了之后又想改了 然后就是一直一片空白

**Comment by gaoyoubo** [comment]
@jeromememory 你现在以前的版本也不能用吗？ 你都试过哪些版本呢？

**Comment by jeromememory** [comment]
@gaoyoubo 我试了1.3.1和1.3.0两个版本 都用不了了

**Comment by jeromememory** [comment]
之前用的几个星期都是没问题的哈

**Comment by gaoyoubo** [comment]
@jeromememory  也没报其他任何错误吗？ 我刚刚自己试了一下，使用没有任何问题啊。 麻烦你去你做一下一下两步操作。
- 第一步，去你的hexo项目中将`node_modules`文件夹删掉，然后重新执行一下`npm install`
- 第二步，备份你的home目录下的`.hexo-client`文件夹（该文件夹下方的是配置文件），然后删掉`.hexo-client`文件夹。

完成以上两步操作之后再重启hexoclient试一下。

**Comment by jeromememory** [comment]
@gaoyoubo 好的 我去试试

**Comment by gaoyoubo** [comment]
@jeromememory 如果开始不行的话， 请使用快捷键: `option + command + i`打开控制台，看下控制台有没有异常，如果有异常请发给我。

**Comment by jeromememory** [comment]
啊可以了 我把home文件夹下的.hexo-client删除后 可以正常使用了 十分感谢

**Comment by gaoyoubo** [comment]
好的，删掉.hexo-client目录之后你的配置会丢失，需要你重新进行配置。 
另外我刚刚加了一个HexoClient的用户群，欢迎加群：618213781

以后有问题可以在群里反馈。

**Comment by jeromememory** [comment]
@gaoyoubo 好像还是有点问题 我重新安装了npm并且删除了.hexo-client，但是无法选择我的hexo安装目录了
