### ISSUE TITLE
mac下突然就空白了 之前一直好用

### ISSUE THREAD

**Issue by jeromememory** [gaoyoubo/hexo-client#68]
贴上界面代码错误：
<strong>We're sorry but hexo-client3 doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>

**Comment by gaoyoubo** [comment]
好的， 我现在看下， 大问题啊。

**Comment by gaoyoubo** [comment]
哦， 你连续提了两个issues，重复了，我将这个关掉了哈。

**Comment by gaoyoubo** [comment]
#67 重复了，关掉这个。
