### ISSUE TITLE
能否提供除了 releases 之外的备用下载地址

### ISSUE THREAD

**Issue by hooray** [gaoyoubo/hexo-client#71]
不知是什么原因，就是下载不下来，不管是在家还是在公司，挂梯子还是没挂梯子，都不行，我太难了。

**Comment by gaoyoubo** [comment]
我用release是因为方便，包自动构建上传的，不需要我手动操作。 有没有其他备用下载服务推荐呢？ 百度云太慢...

**Comment by hooray** [comment]
或者可以用 [gitee](https://gitee.com/) 的`导入 Github 项目`功能，这边更新后，那边直接点个同步好像就可以了。

**Comment by gaoyoubo** [comment]
> ~或者可以用 [gitee](https://gitee.com/) 的`导入 Github 项目`功能，这边更新后，那边直接点个同步好像就可以了。~
> 刚看了发现原来是有同名项目的，只是下载地址还是跳回了 github

是的gitee的releases功能非常不好用。

**Comment by gaoyoubo** [comment]
如果你需要mac版的话， 我可以发一份给你， 因为我这里正好有打包好的mac版

**Comment by hooray** [comment]
> 如果你需要mac版的话， 我可以发一份给你， 因为我这里正好有打包好的mac版

我用win版的，不过刚用电脑连手机的热点下载成功了 😄

**Comment by gaoyoubo** [comment]
OK
