### ISSUE TITLE
无法加载界面，求助

### ISSUE THREAD

**Issue by kiddspace** [gaoyoubo/hexo-client#72]
1. 我运行 npm run electron:serve 命令后后台报错：
Failed to fetch extension, trying 0 more times
Vue Devtools failed to install: Error: net::ERR_CONNECTION_RESET
但是可以打开显示，慢一点。
2. 我运行 npm run electron:build 命令进行打包，打开客户端报如下错误，不知道是我服务端的问题还是客户端的问题；
<img width="509" alt="image" src="https://user-images.githubusercontent.com/9276549/63406869-b9b12200-c41d-11e9-8bc7-1904b80dacff.png">

**Comment by gaoyoubo** [comment]
这个问题其他用户也遇到过， 主要是好因为你主题的原因。因为hexo-client启动的时候会加载你所有的hexo资源，包括主题、插件。 在加载你使用的`next`主题时报错了。 你可以更换其他主题试一下。

**Comment by kiddspace** [comment]
谢啦
