### ISSUE TITLE
右侧的分类展示形式建议修改下

### ISSUE THREAD

**Issue by hooray** [gaoyoubo/hexo-client#73]
![image.png](https://i.loli.net/2019/08/22/39rgNOnT6vD21ds.png)

分类和标签的使用有点差别，标签是同级的，多个标签之间没有关联。而分类是父子级的关系，有点像面包屑导航的意思。（这个属于 Hexo 的特性，没办法改变。）

例如截图中的例子，代表着：

`Git相关` 分类下面的 `Web综合` 分类下面的 `Vue相关` 分类

而并非 3 个平级的分类，所以展示上建议和标签区分开，不然容易让人误解，比如可以换成树形结构的展示。

**Comment by gaoyoubo** [comment]
因为我用的时候一般只会选一个分类，选多个标签，而hexo是支持选多个分类的， 所以为了尊重hexo我也支持了选多分类。 
在我理解的分类其实和标签没啥区别， 在hexo里面处理方式也是和标签一样的。 

另外如果将分类修改为树形菜单我也没想好怎么去布局。

**Comment by hooray** [comment]
哈哈，我的使用方式其实和你是一样的，因为 hexo 的分类使用确实有点迷，所以就不使用多个分类。

既然不方便修改那就这样吧。

**Comment by gaoyoubo** [comment]
感谢你的建议吧。我其实不是一个专业的前端程序员，我是写后端的。 js并非我擅长

**Comment by hooray** [comment]
@gaoyoubo 前同行，哈哈，我以前也写后端
