### ISSUE TITLE
怎么选择博客目录

### ISSUE THREAD

**Issue by harvies** [gaoyoubo/hexo-client#87]
修改博客目录后，打开空白

**Comment by gaoyoubo** [comment]
请确保你正确安装了hexo，并且选择了正确的hexo博客目录。

**Comment by harvies** [comment]
hexo博客目录之前选择过一次，编辑，发布都是正常的，后来那个博客废弃了，重新建了一个，hexo-client还是认的之前的博客名，option+command+i看到的，我的意思是怎么重新设置博客目录

**Comment by gaoyoubo** [comment]
你可以打开hexo-client，在设置那里修改hexo博客地址， 然后重启hexo-client。 

如果还不行的话，可以删掉hexo-client的配置文件，然后重启hexo-client，会引导你重新配置。 

配置文件在：$HOME/.hexo-client  目录。

删除前请先备份配置。

**Comment by harvies** [comment]
> 你可以打开hexo-client，在设置那里修改hexo博客地址， 然后重启hexo-client。
> 
> 如果还不行的话，可以删掉hexo-client的配置文件，然后重启hexo-client，会引导你重新配置。
> 
> 配置文件在：$HOME/.hexo-client 目录。
> 
> 删除前请先备份配置。

试了 还是空白

**Comment by harvies** [comment]
![image](https://user-images.githubusercontent.com/16585330/71905272-c9e65580-31a2-11ea-88f9-ef26ca98dbf4.png)
![image](https://user-images.githubusercontent.com/16585330/71905297-d5d21780-31a2-11ea-8f8c-d93d3e68e745.png)
解决了，原因是这个文件不一致导致，在博客目录重新生成该文件即可
