### ISSUE TITLE
能否使用git的用户名+密码方式部署

### ISSUE THREAD

**Issue by water-mi** [gaoyoubo/hexo-client#88]

**Comment by gaoyoubo** [comment]
是支持的，有个命令行发布的功能。 应该就是你需要的。

**Comment by water-mi** [comment]
> 是支持的，有个命令行发布的功能。 应该就是你需要的。

显示could not read Username

**Comment by gaoyoubo** [comment]
自己去配置啊。将hexo配置好。 他的原理就是帮你执行`hexo generate`和`hexo deploy`

**Comment by water-mi** [comment]
> 自己去配置啊。将hexo配置好。 他的原理就是帮你执行`hexo generate`和`hexo deploy`

好的，谢谢，已经弄好了
